id: PEEEF5601
initial_creation_type: input
source_metadata:
  title: Dzong-ngön Pema Tukchok Dorje
  language: bo
  description: 'Texts by and about Dzong-ngön Pema Tukchok Dorje (rdzong sngon padma
    thugs mchog rdo rje), the incarnation of Dola Jigme Kalzang:'
  volume:
    7a0e405080864442af10c9f399abd72e:
      title: A Simple Method of Transference for Helpless Animals
      parent: Transference
created_at: '2022-02-28T23:12:15.402908'
last_modified_at: '2022-02-28T23:12:15.402910'
statistics:
  total_words: 297
  total_non_words: 29
quality:
  non_words_ratio: 0.1
